/*Inheritance 
Write a java application to maintain information for xyz sports club. The  
sports club wants to store employee details, for each employee store 
id, name, mobile no, emailid, Department, designation, Date of joining. 
Employees are of 3 types salaried employee or contract employee,Vendors. 
	If employee is 
salaried employee, then store basic salary and if it is contract employee then store no of hrs 
worked and per hour rate and if it is vendor then store no_of _employees, amount 
Also store information about members of club 
For each member store id, name, mobile no, emailid, type of membership, amount paid. 
For employee and members, id is autogenerated 
design a menu driven program to perform following 
Calculate net salary by using following formula 

1. 
Salaried Employee  
Basic+DA+HRA-pf 
DA-10% of basic 
HRA – 15% of basic 
Pf – 12% of Basic 

2. 
Contract Employee 
Hr rate * no of hrs worked 

3 Vendor 
amt+Amt*18% GST 
Also store information about members of club 
For each member store id, name, mobile no, emailid, type of membership, amount paid. 
For employee and members, id is autogenerated 
design a menu driven program to perform following 

1. Display All employees (ask user salaried/contract employee display only one type of emplyees 
based on selection) 
2. Search by id 
3. Search by name 
4. Display all employee  
5. calculate salary and display for all emplyees with particular designation 
6. accept department from user and display 5 employees of that department.     
5. Exit */



package Assignment;

import java.util.Scanner;

class Q4TestSportsClub {

    static Q4Employee[] employees = new Q4Employee[5];

    static int employeeCount = 0;

    public static void main(String[] args) {

        Scanner sc = new Scanner(System.in);

        while (true) {

            System.out.println();
            System.out.println("1. Add Employee");
            System.out.println("2. Display Employees by Type");
            System.out.println("3. Search Employee by ID");
            System.out.println("4. Search Employee by Name");
            System.out.println("5. Display All Employees");
            System.out.println("6. Calculate Salary by Designation");
            System.out.println("7. Display 5 Employees by Department");
            System.out.println("8. Exit");

            System.out.println("Enter Choice:");
            int choice = sc.nextInt();

            switch (choice) {

                case 1:

                    if (employeeCount == 5) {
                        System.out.println("Employee limit reached");
                        break;
                    }

                    sc.nextLine();

                    System.out.println("Enter Name:");
                    String name = sc.nextLine();

                    System.out.println("Enter Mobile:");
                    String mobile = sc.nextLine();

                    System.out.println("Enter Email:");
                    String email = sc.nextLine();

                    System.out.println("Enter Department:");
                    String department = sc.nextLine();

                    System.out.println("Enter Designation:");
                    String designation = sc.nextLine();

                    System.out.println("Enter Date of Joining:");
                    String doj = sc.nextLine();

                    System.out.println("1. Salaried Employee");
                    System.out.println("2. Contract Employee");
                    System.out.println("3. Vendor");

                    int type = sc.nextInt();

                    if (type == 1) {

                        System.out.println("Enter Basic Salary:");
                        double basic = sc.nextDouble();

                        employees[employeeCount++] =
                                new Q4SalariedEmployee(name, mobile, email,
                                        department, designation, doj, basic);

                    } else if (type == 2) {

                        System.out.println("Enter Hours Worked:");
                        int hours = sc.nextInt();

                        System.out.println("Enter Rate Per Hour:");
                        double rate = sc.nextDouble();

                        employees[employeeCount++] =
                                new Q4ContractEmployee(name, mobile, email,
                                        department, designation, doj,
                                        hours, rate);

                    } else if (type == 3) {

                        System.out.println("Enter Number of Employees:");
                        int noOfEmployees = sc.nextInt();

                        System.out.println("Enter Amount:");
                        double amount = sc.nextDouble();

                        employees[employeeCount++] =
                                new Q4Vendor(name, mobile, email,
                                        department, designation, doj,
                                        noOfEmployees, amount);
                    }

                    break;

                case 2:

                    System.out.println("1. Salaried Employee");
                    System.out.println("2. Contract Employee");
                    System.out.println("3. Vendor");

                    int t = sc.nextInt();

                    for (int i = 0; i < employeeCount; i++) {

                        if (t == 1 && employees[i] instanceof Q4SalariedEmployee) {
                            employees[i].display();
                            System.out.println();
                        }

                        if (t == 2 && employees[i] instanceof Q4ContractEmployee) {
                            employees[i].display();
                            System.out.println();
                        }

                        if (t == 3 && employees[i] instanceof Q4Vendor) {
                            employees[i].display();
                            System.out.println();
                        }
                    }

                    break;

                case 3:

                    System.out.println("Enter Employee ID:");
                    int id = sc.nextInt();

                    for (int i = 0; i < employeeCount; i++) {

                        if (employees[i].id == id) {
                            employees[i].display();
                            break;
                        }
                    }

                    break;

                case 4:

                    sc.nextLine();

                    System.out.println("Enter Employee Name:");
                    String searchName = sc.nextLine();

                    for (int i = 0; i < employeeCount; i++) {

                        if (employees[i].name.equalsIgnoreCase(searchName)) {
                            employees[i].display();
                            System.out.println();
                        }
                    }

                    break;

                case 5:

                    for (int i = 0; i < employeeCount; i++) {
                        employees[i].display();
                        System.out.println();
                    }

                    break;

                case 6:

                    sc.nextLine();

                    System.out.println("Enter Designation:");
                    String des = sc.nextLine();

                    for (int i = 0; i < employeeCount; i++) {

                        if (employees[i].designation.equalsIgnoreCase(des)) {

                            System.out.println("Employee ID = " + employees[i].id);
                            System.out.println("Name = " + employees[i].name);
                            System.out.println("Salary = " +
                                    employees[i].calculateSalary());

                            System.out.println();
                        }
                    }

                    break;

                case 7:

                    sc.nextLine();

                    System.out.println("Enter Department:");
                    String dept = sc.nextLine();

                    int count = 0;

                    for (int i = 0; i < employeeCount; i++) {

                        if (employees[i].department.equalsIgnoreCase(dept)) {

                            employees[i].display();
                            System.out.println();

                            count++;

                            if (count == 5) {
                                break;
                            }
                        }
                    }

                    break;

                case 8:

                    System.out.println("Program Ended");
                    sc.close();
                    return;

                default:

                    System.out.println("Invalid Choice");
            }
        }
    }
}
